Areas/Admin/Controllers/adBaiHatsController.cs
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteNhacOnl.Models;

namespace WebsiteNhacOnl.Areas.Admin.Controllers
{
    [Authorize]
    public class adBaiHatsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/adBaiHats
        //Sắp xếp theo thứ thự
      /*  public ActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var baiHats = db.BaiHats.AsQueryable();
            switch (sortOrder)
            {
                case "name_desc":
                    baiHats = baiHats.OrderByDescending(s => s.TenBH);
                    break;
                case "Date":
                    baiHats = baiHats.OrderBy(s => s.NgayCapNhat);
                    break;
                case "date_desc":
                    baiHats = baiHats.OrderByDescending(s => s.NgayCapNhat);
                    break;
                default:
                    baiHats = baiHats.OrderBy(s => s.TenBH);
                    break;
            }

            return View(baiHats.ToList());
        }*/


         public ActionResult Index(string searchString)
         {
            //Tìm kiếm
            var baiHats = db.BaiHats.Include(b => b.TheLoai);
            if (!String.IsNullOrEmpty(searchString))
            {
                baiHats = baiHats.Where(s => s.CaSi.Contains(searchString)
                                       || s.TenBH.Contains(searchString)
                                       ||s.TheLoai.TenTL.Contains(searchString)
                                       || s.TacGia.Contains(searchString));
            }

            return View(baiHats.ToList());
         }


        // GET: Admin/adBaiHats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiHat baiHat = db.BaiHats.Find(id);
            if (baiHat == null)
            {
                return HttpNotFound();
            }
            return View(baiHat);
        }

        // GET: Admin/adBaiHats/Create
        public ActionResult Create()
        {
            ViewBag.MaTL = new SelectList(db.TheLoais, "Id", "TenTL");
            return View();
        }

        // POST: Admin/adBaiHats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TenBH,CaSi,TacGia,NgayCapNhat,HinhAnhBH,UrlBH,LoiBH,MaTL")] BaiHat baiHat, HttpPostedFileBase img, HttpPostedFileBase url)
        {
            var path = "";
            var filename = "";
            var filenhac = "";
            if (ModelState.IsValid)
            {
                //them ảnh
                if (img != null)
                {

                    filename = img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/images"), filename);
                    img.SaveAs(path);
                    baiHat.HinhAnhBH = "/Content/images/" + filename; //Lưu ý

                }
                else
                {
                    baiHat.HinhAnhBH = "a.jpg";
                }
                //them nhạc
                if (url != null)
                {
                    filenhac = url.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/music/"), filenhac);
                    url.SaveAs(path);
                    baiHat.UrlBH =  filenhac;
                }
                else
                {
                    baiHat.UrlBH = "a.mp3";
                }
                db.BaiHats.Add(baiHat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaTL = new SelectList(db.TheLoais, "Id", "TenTL", baiHat.MaTL);
            return View(baiHat);
        }

        // GET: Admin/adBaiHats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiHat baiHat = db.BaiHats.Find(id);
            if (baiHat == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTL = new SelectList(db.TheLoais, "Id", "TenTL", baiHat.MaTL);
            return View(baiHat);
        }

        // POST: Admin/adBaiHats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TenBH,CaSi,TacGia,NgayCapNhat,HinhAnhBH,UrlBH,LoiBH,MaTL")] BaiHat baiHat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(baiHat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaTL = new SelectList(db.TheLoais, "Id", "TenTL", baiHat.MaTL);
            return View(baiHat);
        }

        // GET: Admin/adBaiHats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiHat baiHat = db.BaiHats.Find(id);
            if (baiHat == null)
            {
                return HttpNotFound();
            }
            return View(baiHat);
        }

        // POST: Admin/adBaiHats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BaiHat baiHat = db.BaiHats.Find(id);
            db.BaiHats.Remove(baiHat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        //Tải nhạc
        public FileResult Download(string fileName)
        {
            string path = Path.Combine(Server.MapPath("~/Content/music"), fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        //xuất file pdf
        public ActionResult adreport(string searchString)
        {
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Areas/Report"), "CrystalReportBH.rpt"));
            rd.SetDataSource(db.BaiHats.ToList());
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "adBaiHats.pdf");
            }
            catch
            {
                throw;
            }
        }
    }
}

Areas/Admin/Views/adBaiHats/Create.cshtml
@model WebsiteNhacOnl.Models.BaiHat

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />
<h2 style="margin-left:160px;">Thêm mới</h2>
<hr />
<h1> @ViewBag.msg</h1>

@using (Html.BeginForm("Create", "adBaiHats", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="margin-left:100px">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Tên bài hát
            </dt>
        </dl>

        <div class="col-md-10">
            @Html.EditorFor(model => model.TenBH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenBH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Ca sĩ
            </dt>
        </dl>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CaSi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CaSi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Tác giả
            </dt>
        </dl>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Ngày cập nhật
            </dt>
        </dl>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayCapNhat, new { @type = "date", @class = "form-control datepicker", DataFormatString = "{0:yyyy-MM-dd}" })
            @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Hình ảnh bài hát
            </dt>
        </dl>

        <div class="col-md-10">
            <input type="file" name="img" id="img" accept=".jpg,.png,.gif,.jpeg,.bmp" />
            @Html.ValidationMessageFor(model => model.HinhAnhBH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Lời bài hát
            </dt>
        </dl>
        <div class="col-md-10">
           
            @Html.TextAreaFor(model => model.LoiBH, new { htmlAttributes = new { @class = "form-control" }, cols = "60", rows = "15" })
            @Html.ValidationMessageFor(model => model.LoiBH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Link bài hát
            </dt>
        </dl>

        <div class="col-md-10">

            <input type="file" name="url" id="url" accept=".mp3" />
            @Html.ValidationMessageFor(model => model.UrlBH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-left:160px;">
        <dl>
            <dt>
                Mã thể loại
            </dt>
        </dl>

        <div class="col-md-10">
            @Html.DropDownList("MaTL", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaTL, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group" style="margin-left:160px">
        <div class="col-md-offset-2 col-md-10">

            <p class="create" style="color:black;font-size:24px; font-weight:400">
                <input type="submit" value="Thêm mới" class="btn btn-default" />

            </p>

        </div>
    </div>
</div>
}
<hr />
<div style="margin-left:160px">
    @Html.ActionLink("Trở lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<style>
    .create {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }

        .create:hover {
            background-color: wheat;
        }
</style>

Areas/Admin/Views/adBaiHats/Delete.cshtml
@model WebsiteNhacOnl.Models.BaiHat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />

<h2 style="margin-left:160px">Xóa bài hát</h2>
<hr />
<div style="margin-left:250px">



    <dl>
        <dt>
            Tên bài hát
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenBH)
        </dd>

        <dt>
            Ca sĩ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaSi)
        </dd>

        <dt>
            Tác giả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            Hình ảnh bài hát
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhBH)
        </dd>

        <dt>
            Link bài hát
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrlBH)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                <p class="create" style="color:black;font-size:24px; font-weight:400">
                    <input type="submit" value="Xóa" class="btn btn-default" />

                </p>

            </div>
        </div>



    }
</div>
<hr />
<div style="margin-left:170px">
    @Html.ActionLink("Trở lại", "Index")
</div>
<style>
    .create {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }

        .create:hover {
            background-color: wheat;
        }
</style>

Areas/Admin/Views/adBaiHats/Details.cshtml
@model WebsiteNhacOnl.Models.BaiHat

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />
<h2 style="margin-left:160px;">Chi tiết bài hát</h2>
<hr />
<div style="margin-left:250px;">


    <dl class="dl-horizontal">

        <dt>
            Tên bài hát
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenBH)
        </dd>

        <dt>
            Ca sĩ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaSi)
        </dd>

        <dt>
            Tác giả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            Hình ảnh bài hát
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.HinhAnhBH)" alt="Ảnh bài hát" style="width:150px; height:150px" />
        </dd>
        <dt>
            Lời bài hát
        </dt>

        <dd>
            <p>@Html.TextAreaFor(model => model.LoiBH, new { htmlAttributes = new { @class = "form-control" }, cols = "60", rows = "15" })</p>
        </dd>
        <dt>
            Link bài hát
        </dt>

        <dd>
            <p>@Html.DisplayFor(model => model.UrlBH)</p>
            <audio controls>
                <source src="horse.ogg" type="audio/ogg">
                <source src="~/Content/music/@Html.DisplayFor(model => model.UrlBH)" type="audio/mpeg">
                Trình duyệt của bạn không hỗ trợ các yếu tố âm thanh.
            </audio>

        </dd>


    </dl>

</div>
<hr />
<p style="margin-left:  170px">
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Trở lại", "Index")
</p>

Areas/Admin/Views/adBaiHats/Edit.cshtml
@model WebsiteNhacOnl.Models.BaiHat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />

<h2 style="margin-left:160px;">Sửa bài hát</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()





    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div style="margin-left:250px;">


        <dl class="dl-horizontal">

            <dt>
                Tên bài hát
            </dt>

            <dd>
                @Html.EditorFor(model => model.TenBH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenBH, "", new { @class = "text-danger" })
            </dd>

            <dt>
                Ca sĩ
            </dt>

            <dd>
                @Html.EditorFor(model => model.CaSi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaSi, "", new { @class = "text-danger" })
            </dd>

            <dt>
                Tác giả
            </dt>

            <dd>
                @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </dd>

            <dt>
                Ngày cập nhật
            </dt>

            <dd>

                @Html.TextBoxFor(model => model.NgayCapNhat, new { @type = "date", @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </dd>

            <dt>
                Hình ảnh bài hát
            </dt>

            <dd>
                @Html.EditorFor(model => model.HinhAnhBH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnhBH, "", new { @class = "text-danger" })
            </dd>
            <dt>
                Lời bài hát
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.LoiBH, new { htmlAttributes = new { @class = "form-control" }, cols = "60", rows = "15" })
                @Html.ValidationMessageFor(model => model.LoiBH, "", new { @class = "text-danger" })

            </dd>
            <dt>
                Link bài hát
            </dt>

            <dd>
                @Html.EditorFor(model => model.UrlBH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlBH, "", new { @class = "text-danger" })

            </dd>
            <dt>
                Mã thể loại
            </dt>
            <dd>
                @Html.DropDownList("MaTL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTL, "", new { @class = "text-danger" })
            </dd>

        </dl>

    </div>
    <div class="form-group" style="margin-left:250px">
        <div class="col-md-offset-2 col-md-10">

            <p class="create" style="color:black;font-size:24px; font-weight:400">
                <input type="submit" value="Lưu" class="btn btn-default" />

            </p>

        </div>
    </div>

}
<hr />
<div style="margin-left:170px">
    @Html.ActionLink("Trở lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<style>
    .create {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }

        .create:hover {
            background-color: wheat;
        }
</style>

Areas/Admin/Views/adBaiHats/Index.cshtml
@model IEnumerable<WebsiteNhacOnl.Models.BaiHat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<br />
<h1 style="color:blue;text-align:center;font-size:32px">THÊM BÀI HÁT</h1>
<div>
    @Html.Raw(@Html.ActionLink("[replacetext]", "Create").ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/them.png\" height=\"40\">"))
    <a class="btn btn-success" href="@Url.Action("adreport")">Xuất(.pdf)</a>
</div>
<br />
@using (Html.BeginForm())
{
    <form>
        Tìm kiếm: @Html.TextBox("SearchString")
        <button> <img src="~/Content/images/imgweb/search_icon.png" height="20" width="20" /> </button>
    </form>
}
<br />
<table class="table" style="border: 1px solid #A9A9A9; border-radius: 4px; text-align: center">
    <!--  <tr>
          <th>
              @Html.ActionLink("Sắp xếp theo tên", "Index", new { sortOrder = ViewBag.NameSortParm })
          </th>

      </tr>-->
    <tr>
        <th style="border: 1px solid #A9A9A9">
            Tên thể loại
        </th>
        <th style="border: 1px solid #A9A9A9">
            Tên bài hát
        </th>
        <th style="border: 1px solid #A9A9A9">
            Ca sĩ
        </th>
        <th style="border: 1px solid #A9A9A9">
            Tác giả
        </th>
        <th style="border: 1px solid #A9A9A9">
            Ngày cập nhật
        </th>
        <th style="border: 1px solid #A9A9A9">
            Hình ảnh bài hát
        </th>
        <th style="border: 1px solid #A9A9A9">
            Link bài hát
        </th>
        <th style="border: 1px solid #A9A9A9"> Thao tác </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.TheLoai.TenTL)
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.TenBH)
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.CaSi)
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.TacGia)
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>
            <td style="border: 1px solid #A9A9A9">
                <img src="@item.HinhAnhBH" style="height:45px" />
                @*<img src=" @Html.DisplayFor(modelItem => item.HinhAnhBH)" />*@
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.DisplayFor(modelItem => item.UrlBH)
            </td>
            <td style="border: 1px solid #A9A9A9">
                @Html.Raw(@Html.ActionLink("[replacetext]", "Edit", new { id = item.Id }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/edit.png\" height=\"25\">"))
                @Html.Raw(@Html.ActionLink("[replacetext]", "Details", new { id = item.Id }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/details.png\" height=\"25\">"))
                @Html.Raw(@Html.ActionLink("[replacetext]", "Delete", new { id = item.Id }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/delete.png\" height=\"25\">"))
                @Html.Raw(@Html.ActionLink("[replacetext]", "Download", new { fileName = item.UrlBH }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/TaiVe.png\" height=\"25\">"))
            </td>
        </tr>
    }

</table>

Areas/Admin/Views/adBaiHats/adreport.cshtml
@model IEnumerable<WebsiteNhacOnl.Models.BaiHat>

@{
    ViewBag.Title = "adreport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>adreport</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TheLoai.TenTL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenBH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CaSi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TacGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnhBH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlBH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoiBH)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TheLoai.TenTL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenBH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CaSi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TacGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayCapNhat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HinhAnhBH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrlBH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoiBH)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>