Models/BaiHat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebsiteNhacOnl.Models
{
    public class BaiHat
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Tên bài Hát")]
        public string TenBH { get; set; }
        [Display(Name = "Ca sĩ")]
        public string CaSi { get; set; }
        [Display(Name = "Tác giả")]
        public string TacGia { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public DateTime NgayCapNhat { get; set; }
        [Display(Name = "Ảnh bài hát")]
        public string HinhAnhBH { get; set; }
        [Display(Name = "URL Bài hát")]
        public string UrlBH { get; set; }
        [Display(Name = "Lời bài hát")]
        public string LoiBH { get; set; }



        [ForeignKey("TheLoai")]
        public int MaTL { get; set; }
        public TheLoai TheLoai { get; set; }
    }
}

Controllers/BaiHatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteNhacOnl.Models;

using PagedList;
using PagedList.Mvc;

namespace WebsiteNhacOnl.Controllers
{
    public class BaiHatsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: BaiHats
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
         
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

             var baiHats = db.BaiHats.AsQueryable();
           

            if (!String.IsNullOrEmpty(searchString))
            {
                baiHats = baiHats.Where(s => s.CaSi.Contains(searchString)
                                       || s.TenBH.Contains(searchString)
                                       || s.TacGia.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    baiHats = baiHats.OrderByDescending(s => s.TenBH);
                    break;
                case "Date":
                    baiHats = baiHats.OrderBy(s => s.NgayCapNhat);
                    break;
                case "date_desc":
                    baiHats = baiHats.OrderByDescending(s => s.NgayCapNhat);
                    break;
                default:
                    baiHats = baiHats.OrderBy(s => s.TenBH);
                    break;
            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(baiHats.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult NhacTheoTheLoai(int? id)
        {

            var baiHat = from bh in db.BaiHats where bh.MaTL == id select bh;
            return View(baiHat);
        }


        // GET: BaiHats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiHat baiHat = db.BaiHats.Find(id);
            if (baiHat == null)
            {
                return HttpNotFound();
            }
            return View(baiHat);
        }

        public FileResult Download(string fileName)
        {
            string path = Path.Combine(Server.MapPath("~/Content/music"), fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
      

    }
}

Controllers/TheLoaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteNhacOnl.Models;

namespace WebsiteNhacOnl.Controllers
{
    public class TheLoaisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TheLoais
        public ActionResult Index( )
        {
 
            return View(db.TheLoais.ToList());
        }

        // GET: TheLoais/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheLoai theLoai = db.TheLoais.Find(id);
            if (theLoai == null)
            {
                return HttpNotFound();
            }
            return View(theLoai);
        }

        
    }
}

Views/BaiHats/Details.cshtml
@model WebsiteNhacOnl.Models.BaiHat

@{
    ViewBag.Title = "Chi tiết bài hát";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
      rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous">
<link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css”>
<link href="~/Content/CSS/StyleDetails.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="story__images">
                <img src="@Html.DisplayFor(model => model.HinhAnhBH)" alt="" class="story__img">
                <div class="story__square"></div>
            </div>
            <audio controls style="border-style: outset;">
                <source src="horse.ogg" type="audio/ogg">
                <source src="/Content/music/@Html.DisplayFor(model => model.UrlBH)" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </div>
        <div class="col-md-8">
            <div class="rightDetails">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.TenBH)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenBH)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CaSi)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CaSi)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TacGia)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TacGia)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NgayCapNhat)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NgayCapNhat)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LoiBH)
                    </dt>


                    <dd>
                        @Html.TextAreaFor(model => model.LoiBH, new { htmlAttributes = new { @class = "form-control" }, cols = "45", rows = "15" })
                    </dd>

                </dl>
            </div>
            <p>
                <b class="fa fa-reply">
                    @Html.ActionLink("Trở về", "Index")|
                </b>

                <b class="fa fa-download">
                    @Html.ActionLink("Tải Về", "Download", new { fileName = Model.UrlBH })
                </b>

            </p>
        </div>

    </div>
</div>

Views/BaiHats/Index.cshtml
@model PagedList.IPagedList<WebsiteNhacOnl.Models.BaiHat>


@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Bài hát";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
      rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous">
<link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css”>
<link href="~/Content/CSS/StyleBaiHat.css" rel="stylesheet" />
<link href="~/Content/imagehover.min.css" rel="stylesheet" />

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-md-6">
                <b style="font-size:14pt">Tìm kiếm bài hát:</b> @Html.TextBox("SearchString")
                <button> <img src="~/Content/images/imgweb/search_icon.png" height="20" width="20" /> </button>
            </div>
            <div class="col-md-6" style="text-align:left;color:dodgerblue">
                <h2 class="text-center">Music</h2>
            </div>
        </div>
        <hr />
    }
    @foreach (var item in Model)
    {
<div class="musicSong" onclick="setMusicPlay('/Content/music/@item.UrlBH', '@item.HinhAnhBH', '@item.CaSi', '@item.TacGia')">
    <div class="col-md-4">
        <div style="text-align: center; border-bottom: 1px solid maroon; color: dodgerblue">
            <h3>@item.TenBH</h3>
        </div>
        <div class="col-md-8">
            <figure class="imghvr-push-up">
                <img src="@Html.DisplayFor(modelItem => item.HinhAnhBH)" style=" width:150px; height:150px " alt="example-image">
                <figcaption>
                    <img src="~/Content/images/imgweb/play.png" style=" width: 150px; height: 150px " />
                </figcaption><a href="javascript:;"></a>
            </figure>
        </div>
        <div class="col-md-4" style="text-align: left">
            <p>Sáng tác:<br /> <b>@item.TacGia</b> </p>
            <b>
                @Html.Raw(@Html.ActionLink("[replacetext]", "Details", new { id = item.Id }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/icon-xem-chi-tiet.png\" height=\"28\">"))
                <b class="fa fa-download">
                    @Html.ActionLink("Tải Về", "Download", new { fileName = item.UrlBH })
                </b>
            </b>

        </div>

        <div class="col-md-8" style="font-size: 18px; border-top: 1px solid maroon; padding: 2px; text-align: center">
            <b>@item.CaSi</b>
        </div>
        <hr />
    </div>

</div>

        <script>
            function setMusicPlay(musicUrl, imgURL, nameSong, singerSong) {
                var audio = document.getElementById("audio");
                var image = document.getElementById("showI");
                var name = document.getElementById("showN");
                var singer = document.getElementById("showS");

                audio.src = musicUrl;
                image.src = imgURL;
                name.innerText = nameSong;
                singer.innerHTML = singerSong;
            }
        </script>

    }

</div>
@*Tạo lien kết giữa các trang*@
<br />
<div style="text-align:right" >
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>
    

    <div id="playMusic">
        <hr />
        <div id="show">
            <table style="width:100%">
                <tr style="width:100%">
                    <td style="width:15%">
                        <div id="musicDisc">
                            <img id="showI" src="~/Content/images/imgweb/icon_nhac_audio.jpg" class="img-circle" style="width:45px;height:45px" />
                        </div>
                    </td>
                    <td style="width:15%">
                        <div id="musicInfo">
                            <b id="showN"></b> <br />
                            <i id="showS"></i>
                        </div>
                    </td>
                    <td style="width:70%">
                        <audio style="width:100%" id="audio" preload="auto" autoplay="true" loop="true" controls>
                            <source src="~/Content/music/a.mp3" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </td>
                </tr>
            </table>
        </div>
        <script>
            function setShowAlbum(nameAlbum) {
                var listSong = document.getElementsByClassName("musicSong");
                for (var i = 0; i < listSong.length; i++) {
                    if (listSong[i].getElementsByTagName('i')[0].innerText != '(' + nameAlbum + ')') {
                        listSong[i].style.display = "none";
                    }
                    else {
                        listSong[i].style.display = "block";
                    }
                }
            }
        </script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </div>







    @*
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TheLoai.TenTL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TenBH)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CaSi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TacGia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayCapNhat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HinhAnhBH)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UrlBH)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LoiBH)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TheLoai.TenTL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenBH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CaSi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TacGia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayCapNhat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HinhAnhBH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UrlBH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoiBH)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>*@

Views/BaiHats/NhacTheoTheLoai.cshtml
@model IEnumerable<WebsiteNhacOnl.Models.BaiHat>

@{
    ViewBag.Title = "NhacTheoTheLoai";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="~/Content/imagehover.min.css" rel="stylesheet" />
<a href="@Url.Action("Index","TheLoais",new { })" style="font-size:20px"></a>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="musicSong" onclick="setMusicPlay('/Content/music/@item.UrlBH', '@item.HinhAnhBH', '@item.CaSi', '@item.TacGia')">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4" style="padding: 10px 1px 1px 1px; text-align: right">
                            <figure class="imghvr-push-up">
                                <img src="@Html.DisplayFor(modelItem => item.HinhAnhBH)" style=" width:60px; height:60px " alt="example-image">
                                <figcaption>
                                    <img src="~/Content/images/imgweb/play.png" style=" width:60px; height:60px " />
                                </figcaption><a href="javascript:;"></a>
                            </figure>
                        </div>
                        <div class="col-md-4" style=" color: DodgerBlue; font-family: Times New Roman, Times, serif; padding: 1px 1px 1px 5px">
                            <h4> @Html.DisplayFor(modelItem => item.TenBH) </h4>
                            <i>
                                (@Html.DisplayFor(modelItem => item.CaSi)) <br />
                                @Html.Raw(@Html.ActionLink("[replacetext]", "Details", new { id = item.Id }).ToHtmlString().Replace("[replacetext]", " <img src=\"/Content/images/imgweb/icon-xem-chi-tiet.png\" height=\"28\">"))
                            </i>

                        </div>
                        <div class="col-md-4 p-3" style="padding: 1px 1px 1px 1px; text-align: left">
                            <b class="fa fa-download">
                                @Html.ActionLink("Tải Về", "Download", new { fileName = item.UrlBH })
                            </b>
                        </div>

                    </div>
                </div>
                

            </div>

            <script>
                function setMusicPlay(musicUrl, imgURL, nameSong, singerSong) {
                    var audio = document.getElementById("audio");
                    var image = document.getElementById("showI");
                    var name = document.getElementById("showN");
                    var singer = document.getElementById("showS");

                    audio.src = musicUrl;
                    image.src = imgURL;
                    name.innerText = nameSong;
                    singer.innerHTML = singerSong;
                }
            </script>


        }
    </div>
    <div id="playMusic">
        <hr />
        <div id="show">
            <table style="width:100%">
                <tr style="width:100%">
                    <td style="width:15%">
                        <div id="musicDisc">
                            <img id="showI" src="~/Content/images/imgweb/icon_nhac_audio.jpg" class="img-circle" style="width:45px;height:45px" />
                        </div>
                    </td>
                    <td style="width:15%">
                        <div id="musicInfo">
                            <b id="showN"></b> <br />
                            <i id="showS"></i>
                        </div>
                    </td>
                    <td style="width:70%">
                        <audio style="width:100%" id="audio" preload="auto" autoplay="true" loop="true" controls>
                            <source src="~/Content/music/a.mp3" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </td>
                </tr>
            </table>
        </div>
        <script>
            function setShowAlbum(nameAlbum) {
                var listSong = document.getElementsByClassName("musicSong");
                for (var i = 0; i < listSong.length; i++) {
                    if (listSong[i].getElementsByTagName('i')[0].innerText != '(' + nameAlbum + ')') {
                        listSong[i].style.display = "none";
                    }
                    else {
                        listSong[i].style.display = "block";
                    }
                }
            }
        </script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </div>
</div>